spring.application.name=charang

# Tomcat Ã¬ÂÂÃ«Â²ÂÃ«Â¥Â¼ Ã«ÂÂ´Ã¬ÂÂ¥Ã«ÂÂÃ¬ÂÂ´ Ã¬ÂÂÃ«ÂÂ¤.
# Ã¬ÂÂÃ«ÂÂ Ã­ÂÂ¬Ã­ÂÂ¸Ã«Â²ÂÃ­ÂÂ¸Ã«ÂÂ8080Ã¬ÂÂ¸Ã«ÂÂ° => 8090Ã¬ÂÂ¼Ã«Â¡Â Ã«Â³ÂÃªÂ²Â½Ã­ÂÂ¨
# Tomcat
server.port=8090
# Dev Tools
spring.devtools.restart.enabled=true
# Thymeleaf #Ã¬Â£Â¼Ã¬ÂÂ
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mariadb:3306/rentcar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678

# Mybatis
mybatis.config-location=classpath:mybatis/config/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mappers/*.xml

# [Ã¬Â¶ÂÃªÂ°Â] MyBatis SQL Ã«Â¡ÂÃªÂ·Â¸ Ã¬Â¶ÂÃ«Â Â¥ Ã¬ÂÂ¤Ã¬Â Â
# Ã­ÂÂ¨Ã­ÂÂ¤Ã¬Â§Â ÃªÂ²Â½Ã«Â¡Â(com.green.member.mapper)Ã¬ÂÂ Ã«Â¡ÂÃªÂ·Â¸ Ã«Â ÂÃ«Â²Â¨Ã¬ÂÂ DEBUGÃ«Â¡Â Ã¬ÂÂ¤Ã¬Â ÂÃ­ÂÂÃ«Â©Â´ 
# Ã¬ÂÂ¤Ã­ÂÂÃ«ÂÂÃ«ÂÂ SQLÃ«Â¬Â¸ÃªÂ³Â¼ Ã¬Â ÂÃ«ÂÂ¬Ã«ÂÂÃ«ÂÂ Ã­ÂÂÃ«ÂÂ¼Ã«Â¯Â¸Ã­ÂÂ°(? ÃªÂ°Â)Ã«Â¥Â¼ Ã¬Â½ÂÃ¬ÂÂÃ¬ÂÂÃ¬ÂÂ Ã«Â³Â¼ Ã¬ÂÂ Ã¬ÂÂÃ¬ÂÂµÃ«ÂÂÃ«ÂÂ¤.
logging.level.cha.booking.mapper=DEBUG
logging.level.cha.branch.mapper=DEBUG
logging.level.cha.car.mapper=DEBUG
logging.level.cha.inquiry.mapper=DEBUG
logging.level.cha.manager.mapper=DEBUG
logging.level.cha.notice.mapper=DEBUG
logging.level.cha.user.mapper=DEBUG

# [Ã¬ÂÂ Ã­ÂÂ] Ã«Â§ÂÃ¬ÂÂ½ Ã¬ÂÂ¤Ã­ÂÂÃ«Â§Â Ã«Â¶ÂÃ­ÂÂ¸Ã¬ÂÂ Ã¬Â ÂÃ«Â°ÂÃ¬Â ÂÃ¬ÂÂ¸ DB Ã¬ÂÂ°ÃªÂ²Â° Ã¬ÂÂÃ­ÂÂÃ«ÂÂ Ã¬ÂÂ¤Ã¬Â Â Ã«Â¡ÂÃªÂ·Â¸Ã«Â¥Â¼ Ã«Â³Â´ÃªÂ³Â  Ã¬ÂÂ¶Ã«ÂÂ¤Ã«Â©Â´ Ã¬ÂÂÃ«ÂÂÃ«ÂÂ Ã¬Â¶ÂÃªÂ°ÂÃ­ÂÂÃ¬ÂÂ¸Ã¬ÂÂ.
# logging.level.org.springframework.jdbc=DEBUG

# íì¼ í¬ê¸° ì íë íìì í¨ê» ì¤ì 
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# 1. ë©í°íí¸ íí¸ ê°ì ì í (íë 27ê° + ì´ë¯¸ì§ 2ê° + ì¬ì ë¶) 
#spring.servlet.multipart.file-count-limit=100 
# 2. í°ìº£ íë¼ë¯¸í° ê°ì ì í (ê¸°ë³¸ê° 1000ì´ì§ë§ ëªìì ì¼ë¡ ì¤ì ) 
#server.tomcat.max-parameter-count=1000 
# 3. (ì¤ì) í°ìº£ì ë©í°íí¸ ì²ë¦¬ë¥¼ ì¤íë§ ì¤ì ì ìì í ë§¡ê¹ 
#spring.servlet.multipart.enabled=true

# 메일 인증번호 보내기 설정
# Gmail SMTP (JavaMailSender)
# son20032002@gmail.com -> 발신자(개발자) 이메일
# rbfskmqdynhdviqr -> 발신자(개발자)에게 Google Authenticator어플이 보내는 앱 인증 비밀번호 ?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=son20032002@gmail.com
spring.mail.password=rbfskmqdynhdviqr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



